config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  resources :stories do
    resources :comments
  end

  resources :comments do
    resources :comments
  end

  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :commentable, polymorphic: true

  has_many :comments, as: :commentable

end

app/models/story.rb
class Story < ApplicationRecord

  has_many :comments, as: :commentable

  validates :title, presence: true,
            length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :find_commentable

  def new
    @comment = Comment.new
  end

  def create
    @comment = @commentable.comments.new comment_params

    if @comment.save
      redirect_back(fallback_location: root_path)
    else
      @comment.errors[:base] << "Your comment wasn't posted!"
      redirect_back(fallback_location: root_path)
    end

  end

  private

  def comment_params
    params.require(:comment).permit(:commentor, :body)
  end

  def find_commentable
    @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
    @commentable = Story.find_by_id(params[:story_id]) if params[:story_id]
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  def index
    @stories = Story.all
  end

  def show
    @story = Story.find(params[:id])
  end

  def new
    @story = Story.new
  end

  def edit
    @story = Story.find(params[:id])
  end

  def create
    @story = Story.new(story_params)

    if @story.save
      redirect_to story_path(@story)
    else
      render 'new'
    end
  end

  def update
    @story = Story.find(params[:id])

    if @story.update(story_params)
      redirect_to story_path(@story)
    else
      render 'edit'
    end
  end

  def destroy
    @story = Story.find(params[:id])
    @story.destroy

    redirect_to stories_path
  end


  private

  def story_params
    params.require(:story).permit(:title, :text)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<li>
  Comment by: <%= comment.commentor %> > <%= comment.body %> -
  <small>Submitted <%= time_ago_in_words(comment.created_at) %> ago</small>

  <%= form_for [comment, Comment.new] do |f| %>
      <%= f.text_field :commentor, placeholder: "Your name" %><br/>
      <%= f.text_area :body, placeholder: "Add a Reply" %><br/>
      <%= f.submit "Reply"  %>
  <% end %>

  <%= form_with(model: [comment, Comment.new]) do |f| %>
      <%= f.text_field :commentor, placeholder: "Your name" %><br/>
      <%= f.text_area :body, placeholder: "Add a Reply" %><br/>
      <%= f.submit "Reply" %>
  <% end %>

  <ul>
    <%= render partial: 'comments/comment', collection: comment.comments %>
  </ul>

</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myblog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stories/_form.html.erb
<%= form_for @story do |f| %>

    <% if @story.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@story.errors.count, "error") %> prohibited
            this Story from being saved:
          </h2>
          <ul>
            <% @story.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/stories/edit.html.erb
<h1>Edit Story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<h1>Listing stories</h1>

<%= link_to 'New story', new_story_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>

  <% @stories.each do |story| %>
      <tr>
        <td><%= story.title %></td>
        <td><%= story.text %></td>
        <td><%= link_to 'Show', story_path(story) %></td>
        <td><%= link_to 'Edit', edit_story_path(story) %></td>
        <td><%= link_to 'Destroy', story_path(story),
                        method: :delete,
                        data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

app/views/stories/new.html.erb
<h1>New Story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @story.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @story.text %>
</p>

<h3>Comments</h3>

<%= form_with(model: [@story, Comment.new]) do |f| %>
    <%= f.text_field :commentor, placeholder: "Commentor" %><br/>
    <%= f.text_area :body, placeholder: "Add a comment" %><br/>
    <%= f.submit "Add Comment" %>
<% end %>

<ul>
  <%= render(partial: 'comments/comment', collection: @story.comments) %>
</ul>


<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>

app/views/welcome/index.html.erb
<h1>Well hello there Rail :P</h1>
<%= link_to 'My Blog', controller: 'stories' %>